package com.university.studmanager.exceptions;

public enum ErrorCodes {

    UNKNOWN,
    TECHNICAL_ERROR,
    ENTITY_NOT_FOUND,
    PHYSICAL_FILE_NOT_FOUND,
    USER_ALREADY_EXISTS,
    FACULTY_ALREADY_EXISTS,
    DEPARTMENT_ALREADY_EXISTS,
    SERIE_ALREADY_EXISTS,
    GRUPA_ALREADY_EXISTS,
    MATERIE_ALREADY_EXISTS,
    STUDENT_ALREADY_EXISTS,
    SECRETAR_ALREADY_EXISTS,
    AN_ALREADY_EXISTS,
    WRONG_PASSWORD,
    CANNOT_ADD,
    CANNOT_UPDATE,
    CANNOT_DELETE,
    MAIL_SEND_FAILED,
    USER_NOT_FOUND
}
