-- liquibase formatted sql

-- changeset liquibase:1
CREATE TABLE ADMINISTRATOR
(
    ID_ADMINISTRATOR SERIAL,
    ID_USER          BIGINT NOT NULL,
    PRIMARY KEY (ID_ADMINISTRATOR)
);

-- changeset liquibase:2
CREATE TABLE AN
(
    ID_AN          SERIAL,
    NR_AN          BIGINT,
    ID_DEPARTAMENT BIGINT NOT NULL,
    PRIMARY KEY (ID_AN)
);

-- changeset liquibase:3
CREATE TABLE CATALOG
(
    ID_CATALOG SERIAL,
    NOTA       BIGINT,
    ID_MATERIE BIGINT NOT NULL,
    ID_STUDENT BIGINT NOT NULL,
    PRIMARY KEY (ID_CATALOG)
);

-- changeset liquibase:4
CREATE TABLE DEPARTAMENT
(
    ID_DEPARTAMENT SERIAL,
    DENUMIRE       varchar(255),
    ID_FACULTATE   BIGINT NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENT)
);

-- changeset liquibase:5
CREATE TABLE FACULTATE
(
    ID_FACULTATE SERIAL,
    DENUMIRE     varchar(255),
    PRIMARY KEY (ID_FACULTATE)
);

-- changeset liquibase:6
CREATE TABLE FACULTATE_ADMINISTRATORI_INT
(
    ID_FACULTATE_ADMINISTRATORI SERIAL,
    ID_FACULTATE                SERIAL,
    ID_ADMINISTRATOR            SERIAL,
    PRIMARY KEY (ID_FACULTATE_ADMINISTRATORI, ID_FACULTATE, ID_ADMINISTRATOR)
);

-- changeset liquibase:7
CREATE TABLE GRUPA
(
    ID_GRUPA SERIAL,
    DENUMIRE varchar(255),
    ID_SERIE BIGINT NOT NULL,
    PRIMARY KEY (ID_GRUPA)
);

-- changeset liquibase:8
CREATE TABLE MATERIE
(
    ID_MATERIE         SERIAL,
    DENUMIRE           varchar(255),
    NR_ORE             BIGINT,
    SEMESTRU           BIGINT,
    ID_AN              BIGINT NOT NULL,
    ID_PLAN_INVATAMANT BIGINT NOT NULL,
    PRIMARY KEY (ID_MATERIE)
);

-- changeset liquibase:9
CREATE TABLE PLAN_INVATAMANT
(
    ID_PLAN_INVATAMANT SERIAL,
    ID_AN              BIGINT NOT NULL,
    PRIMARY KEY (ID_PLAN_INVATAMANT)
);

-- changeset liquibase:10
CREATE TABLE SECRETAR
(
    ID_SECRETAR    SERIAL,
    ID_DEPARTAMENT BIGINT NOT NULL,
    ID_USER        BIGINT NOT NULL,
    PRIMARY KEY (ID_SECRETAR)
);

-- changeset liquibase:11
CREATE TABLE SERIE
(
    ID_SERIE SERIAL,
    DENUMIRE varchar(255),
    ID_AN    BIGINT NOT NULL,
    PRIMARY KEY (ID_SERIE)
);

-- changeset liquibase:12
CREATE TABLE STUDENT
(
    ID_STUDENT     SERIAL,
    NR_MATRICOL    varchar(255),
    CNP            varchar(255),
    SERIE_CI       varchar(255),
    NUME           varchar(255),
    PRENUME        varchar(255),
    ADRESA         varchar(255),
    DATA_NASTERE   date,
    ID_USER        BIGINT NOT NULL,
    ID_FACULTATE   BIGINT NOT NULL,
    ID_DEPARTAMENT BIGINT NOT NULL,
    ID_AN          BIGINT NOT NULL,
    ID_SERIE       BIGINT NOT NULL,
    ID_GRUPA       BIGINT NOT NULL,
    PRIMARY KEY (ID_STUDENT)
);

-- changeset liquibase:13
CREATE TABLE USERS
(
    ID_USER    SERIAL,
    FIRST_NAME varchar(255),
    LAST_NAME  varchar(255),
    EMAIL      varchar(255),
    PASSWORD   varchar(255),
    ROLE       varchar(255),
    PRIMARY KEY (ID_USER)
);

-- changeset liquibase:14
ALTER TABLE ADMINISTRATOR
    ADD CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

-- changeset liquibase:15
ALTER TABLE AN
    ADD CONSTRAINT ID_DEPARTAMENT FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENT (ID_DEPARTAMENT);

-- changeset liquibase:16
ALTER TABLE CATALOG
    ADD CONSTRAINT ID_MATERIE FOREIGN KEY (ID_MATERIE) REFERENCES MATERIE (ID_MATERIE);

-- changeset liquibase:17
ALTER TABLE CATALOG
    ADD CONSTRAINT ID_STUDENT FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT (ID_STUDENT);

-- changeset liquibase:18
ALTER TABLE DEPARTAMENT
    ADD CONSTRAINT ID_FACULTATE FOREIGN KEY (ID_FACULTATE) REFERENCES FACULTATE (ID_FACULTATE);

-- changeset liquibase:19
ALTER TABLE FACULTATE_ADMINISTRATORI_INT
    ADD CONSTRAINT ID_FACULTATE FOREIGN KEY (ID_FACULTATE) REFERENCES FACULTATE (ID_FACULTATE);

-- changeset liquibase:20
ALTER TABLE FACULTATE_ADMINISTRATORI_INT
    ADD CONSTRAINT ID_ADMINISTRATOR FOREIGN KEY (ID_ADMINISTRATOR) REFERENCES ADMINISTRATOR (ID_ADMINISTRATOR);

-- changeset liquibase:21
ALTER TABLE GRUPA
    ADD CONSTRAINT ID_SERIE FOREIGN KEY (ID_SERIE) REFERENCES SERIE (ID_SERIE);

-- changeset liquibase:22
ALTER TABLE MATERIE
    ADD CONSTRAINT ID_AN FOREIGN KEY (ID_AN) REFERENCES AN (ID_AN);

-- changeset liquibase:23
ALTER TABLE MATERIE
    ADD CONSTRAINT ID_PLAN_INVATAMANT FOREIGN KEY (ID_PLAN_INVATAMANT) REFERENCES PLAN_INVATAMANT (ID_PLAN_INVATAMANT);

-- changeset liquibase:24
ALTER TABLE PLAN_INVATAMANT
    ADD CONSTRAINT ID_AN FOREIGN KEY (ID_AN) REFERENCES AN (ID_AN);

-- changeset liquibase:25
ALTER TABLE SECRETAR
    ADD CONSTRAINT ID_DEPARTAMENT FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENT (ID_DEPARTAMENT);

-- changeset liquibase:26
ALTER TABLE SECRETAR
    ADD CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

-- changeset liquibase:27
ALTER TABLE SERIE
    ADD CONSTRAINT ID_AN FOREIGN KEY (ID_AN) REFERENCES AN (ID_AN);

-- changeset liquibase:28
ALTER TABLE STUDENT
    ADD CONSTRAINT ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID_USER);

-- changeset liquibase:29
ALTER TABLE STUDENT
    ADD CONSTRAINT ID_FACULTATE FOREIGN KEY (ID_FACULTATE) REFERENCES FACULTATE (ID_FACULTATE);

-- changeset liquibase:30
ALTER TABLE STUDENT
    ADD CONSTRAINT ID_DEPARTAMENT FOREIGN KEY (ID_DEPARTAMENT) REFERENCES DEPARTAMENT (ID_DEPARTAMENT);

-- changeset liquibase:31
ALTER TABLE STUDENT
    ADD CONSTRAINT ID_AN FOREIGN KEY (ID_AN) REFERENCES AN (ID_AN);

-- changeset liquibase:32
ALTER TABLE STUDENT
    ADD CONSTRAINT ID_SERIE FOREIGN KEY (ID_SERIE) REFERENCES SERIE (ID_SERIE);

-- changeset liquibase:33
ALTER TABLE STUDENT
    ADD CONSTRAINT ID_GRUPA FOREIGN KEY (ID_GRUPA) REFERENCES GRUPA (ID_GRUPA);

-- changeset liquibase:34
ALTER TABLE secretar
    ADD COLUMN NUME VARCHAR(255);

-- changeset liquibase:35
ALTER TABLE secretar
    ADD COLUMN PRENUME VARCHAR(255);
